// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zpfavpbaehnxgcigofja.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpwZmF2cGJhZWhueGdjaWdvZmphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzODQzMTgsImV4cCI6MjA2NDk2MDMxOH0.2VLgSlZiScFObPQUzcW5CK6lcDeZVnQ1pCuh3PWp3k0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);